version: "3.8"

services:
  postgres-test:
    image: postgres:15
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: socialdb_test
    ports:
      - "5433:5432"

  redis-test:
    image: redis:7
    ports:
      - "6380:6379"

  kafka-test:
    image: wurstmeister/kafka
    environment:
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9093"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-test:2181
    ports:
      - "9093:9092"
    depends_on:
      - zookeeper-test

  zookeeper-test:
    image: wurstmeister/zookeeper
    ports:
      - "2182:2181"

  neo4j-test:
    image: neo4j:5
    environment:
      NEO4J_AUTH: neo4j/neo4jpass
    ports:
      - "7475:7474"
      - "7688:7687"
