global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/actuator/prometheus'

  - job_name: 'feed-api'
    static_configs:
      - targets: ['localhost:8081']
    metrics_path: '/actuator/prometheus'

  - job_name: 'feed-ingestor'
    static_configs:
      - targets: ['localhost:8090']
    metrics_path: '/actuator/prometheus'

  - job_name: 'feed-ranker'
    static_configs:
      - targets: ['localhost:8100']
    metrics_path: '/actuator/prometheus'
